In [1]:
import math3d
import numpy as np

# Vector class

In [2]:
a = math3d.Vector(1,2,3)
b = math3d.Vector(4,5,position=False)
c = math3d.Vector(position=True)

print(a)
print(b)
print(c)

<Vector: (1.00000, 2.00000, 3.00000)>
<Vector: (4.00000, 5.00000, 0.00000)>
<Vector: (0.00000, 0.00000, 0.00000)>


In [3]:
d = a.copy()
print(d)

<Vector: (1.00000, 2.00000, 3.00000)>


In [4]:
a.x, a.y, a.z

(1.0, 2.0, 3.0)

In [5]:
a.x = 9
a

<Vector: (9.00000, 2.00000, 3.00000)>

In [6]:
a[2]

3.0

In [7]:
a[2] = -3
a

<Vector: (9.00000, 2.00000, -3.00000)>

In [8]:
a == d

False

In [9]:
b.is_position

False

In [10]:
a.projection(d)

<Vector: (0.28571, 0.57143, 0.85714)>

In [11]:
a.angle(b)

0.73627923789254002

In [12]:
a.signed_angle(b)

0.73627923789254002

In [13]:
a.length

9.6953597148326587

In [14]:
a.length_squared

94.0

In [15]:
n = a.normalized
n

<Vector: (0.92828, 0.20628, -0.30943)>

In [16]:
a.dist(b)

6.5574385243020004

In [17]:
(a - b).length

6.5574385243020004

In [18]:
a.cross_operator

array([[ 0.,  3.,  2.],
       [-3.,  0., -9.],
       [-2.,  9.,  0.]])

In [19]:
a.alt_cross_operator

array([[ 0.,  3.,  2.],
       [-3.,  0., -9.],
       [-2.,  9.,  0.]])

In [20]:
a.cross(b)

<Vector: (15.00000, -12.00000, 37.00000)>

In [21]:
a.angle(a.cross(b)) * 180/np.pi

90.0

In [22]:
a.array

array([ 9.,  2., -3.])

In [23]:
a.list

[9.0, 2.0, -3.0]

In [24]:
a.matrix

matrix([[ 9.],
        [ 2.],
        [-3.]])

In [25]:
a.column

array([[ 9.],
       [ 2.],
       [-3.]])

In [26]:
a - b

<Vector: (5.00000, -3.00000, -3.00000)>

In [27]:
a * b

46.0

In [28]:
0.3 * a * 2.0

<Vector: (5.40000, 1.20000, -1.80000)>

In [29]:
a / 0.3

<Vector: (30.00000, 6.66667, -10.00000)>

In [30]:
a + d

<Vector: (10.00000, 4.00000, 0.00000)>

In [31]:
-b

<Vector: (-4.00000, -5.00000, -0.00000)>

In [32]:
math3d.Vector.ex

<Vector: (1.00000, 0.00000, 0.00000)>

In [33]:
math3d.Vector.e2

<Vector: (0.00000, 0.00000, 1.00000)>

In [47]:
math3d.Vector.new_random_unit_vector()

<Vector: (-0.24476, 0.85771, -0.45214)>

In [37]:
from math3d import Vector


In [48]:
%%time

r0 = Vector()
v0 = Vector.ex * 0.03

dt = 0.1
t = 0
while True:
    r = r + v0 * dt
    t = t + dt
    if r.x > 1500:
        break

print(t)

49900.09999955435


In [41]:
from pprint import pprint
pprint(Vector.__dict__)

mappingproxy({'__add__': <function Vector.__add__ at 0x7f3da095d2f0>,
              '__copy__': <function Vector.__copy__ at 0x7f3da095c048>,
              '__deepcopy__': <function Vector.__deepcopy__ at 0x7f3da095c0d0>,
              '__dict__': <attribute '__dict__' of 'Vector' objects>,
              '__div__': <function Vector.__truediv__ at 0x7f3da095d268>,
              '__doc__': 'A Vector is a 3D vector (member of R3) with standard '
                         'Euclidian\n'
                         '    operations.',
              '__eq__': <function Vector.__eq__ at 0x7f3da095c400>,
              '__getattr__': <function Vector.__getattr__ at 0x7f3da095c1e0>,
              '__getitem__': <function Vector.__getitem__ at 0x7f3da095c2f0>,
              '__hash__': None,
              '__iadd__': <function Vector.__iadd__ at 0x7f3da095d378>,
              '__imul__': <function Vector.__imul__ at 0x7f3da095d158>,
              '__init__': <function Vector.__init__ at 0x7f3da0952f28>